### ISSUE TITLE
Consider using Component for system state management.

### ISSUE THREAD

**Issue by jrdoane** [kelvin-mai/clj-contacts#1]
This is just a suggestion, but I've found that [Component](https://github.com/stuartsierra/component) does an excellent job at describing the creation and destruction of a system for a Clojure back-end. It's a far more controlled way to handle spinning up and tearing down the system without having to manage atoms all over the place for things like web servers or connection pools. I highly recommend it.

**Comment by kelvin-mai** [comment]
Thanks Jon. This is kinda my first full stack clj project, so I appreciate it.
